language: python
python:
 - "3.4"
sudo: false
env:
 - TOX_ENV=py34
install:
 - pip install tox
 - pip install coveralls
 - pip install ezhost
script:
 - tox -e $TOX_ENV
 - ezhost -h
after_success:
  coveralls